### ISSUE TITLE
Something about your code

### ISSUE THREAD

**Issue by sim-l3** [shikorab/SceneGraph#3]
I notice that you have used some images (i.e., SGP architecture) do not exist in the paper. Therefore, I am wondering whether it is the code for the NIPS 2018 paper "Mapping Images to Scene Graphs with Permutation-Invariant Structured Prediction" or not?

**Comment by roeiherz** [comment]
It is.

**Comment by sim-l3** [comment]
Thanks for your reply, there is one more thing I am confused about is whether the result of pixel2graph cited in your paper has used the RPN or not. It seems that pixe2graph has achieved a much higher performance than in the original paper.

**Comment by sim-l3** [comment]
> It is.

Thanks for your reply, there is one more thing I am confused about is whether the result of pixel2graph cited in your paper has used the RPN or not. It seems that pixe2graph has achieved a much higher performance than in the original paper.
