### ISSUE TITLE
How to get the feature of the relationship

### ISSUE THREAD

**Issue by sim-l3** [shikorab/SceneGraph#4]
In your paper, you mentioned that you re-use feature learned by the pre-trained object detector without using LSTM or context. Since the object detector only gets the feature of the object, you use the union-box feature to represent the feature of the relationship, right?

**Comment by shikorab** [comment]
We use the baseline detector to get initial probabilities of both the object and the relations.
Our network gets those probabilities as an input.
Details about the detector (the baseline version) can be found here:
github.com/rowanz/neural-motif
https://arxiv.org/pdf/1711.06640v2.pdf
